# Generated by Django 4.2.7 on 2025-10-12 17:25

import detector.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=detector.models.upload_to)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("detected_objects", models.JSONField(blank=True, default=list)),
                ("confidence_scores", models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
