# Generated by Django 4.2.7 on 2025-10-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imageupload",
            old_name="confidence_scores",
            new_name="detection_indicators",
        ),
        migrations.RemoveField(
            model_name="imageupload",
            name="detected_objects",
        ),
        migrations.AddField(
            model_name="imageupload",
            name="ai_caption",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="imageupload",
            name="analysis_details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="imageupload",
            name="confidence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="imageupload",
            name="is_ai_generated",
            field=models.BooleanField(default=False),
        ),
    ]
