# Generated by Django 4.2.7 on 2025-10-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "detector",
            "0002_rename_confidence_scores_imageupload_detection_indicators_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="imageupload",
            name="feedback_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="imageupload",
            name="feedback_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageupload",
            name="method",
            field=models.CharField(default="unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="imageupload",
            name="user_feedback",
            field=models.CharField(
                blank=True,
                choices=[
                    ("correct", "Correct"),
                    ("incorrect", "Incorrect"),
                    ("unsure", "Unsure"),
                    ("", "No Feedback"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
