# Generated by Django 4.2.7 on 2025-10-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0003_add_user_feedback_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="MethodPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method_name", models.CharField(max_length=50, unique=True)),
                ("total_detections", models.IntegerField(default=0)),
                ("correct_detections", models.IntegerField(default=0)),
                ("incorrect_detections", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Method Performance",
                "verbose_name_plural": "Method Performances",
            },
        ),
    ]
